// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Michaël Giovanni Jules",
            "url": "https://mgjules.dev",
            "email": "julesmichaelgiovanni@gmail.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "get": {
                "description": "checks if server is running",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "core"
                ],
                "summary": "Health Check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/health.CheckerResult"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/health.CheckerResult"
                        }
                    }
                }
            }
        },
        "/api/minion": {
            "get": {
                "description": "returns the minion's introduction",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "core"
                ],
                "summary": "Minion introduction",
                "responses": {
                    "200": {
                        "description": "My name is '{name}' and I have a secret key '{key}'.",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/version": {
            "get": {
                "description": "checks the server's version",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "core"
                ],
                "summary": "Health Check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/build.Info"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "build.Info": {
            "type": "object",
            "properties": {
                "dirty_build": {
                    "type": "boolean"
                },
                "go_version": {
                    "type": "string"
                },
                "last_commit": {
                    "type": "string"
                },
                "revision": {
                    "type": "string"
                }
            }
        },
        "health.CheckResult": {
            "type": "object",
            "properties": {
                "error": {
                    "description": "Error contains the check error message, if the check failed.",
                    "type": "string"
                },
                "status": {
                    "description": "Status is the availability status of a component.",
                    "type": "string"
                },
                "timestamp": {
                    "description": "Timestamp holds the time when the check was executed.",
                    "type": "string"
                }
            }
        },
        "health.CheckerResult": {
            "type": "object",
            "properties": {
                "details": {
                    "description": "Details contains health information for all checked components.",
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/health.CheckResult"
                    }
                },
                "status": {
                    "description": "Status is the aggregated system availability status.",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "v1.0.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Minion",
	Description:      "A little minion that can be replicated to create more minions.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
